### ISSUE TITLE
Tessel Hackathon: Javascript-powered Hardware

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#2]
Technical Machine is coming up from Berkley with some hackathon kits and will teach everyone how to bring their knowledge of Javascript from the browser to the real world.

There will only be 40 spots available so this will require an RSVP with a hard upper bound.

Managing talk proposals is still a work in progress, so don't think of this as anything quite official. I'm just trying to get things out of my head and written down.

### Tasks
* [x] Will the Tessel wifi module work with Hacker Lab's Terms of Service agreement prompt?

* [x] Get VGA adapter for MacBooks

* [x] Get some bottled water for staff

##### 5:30pm Preparation

* Get Tim fed (if needed)

* Get space setup (chairs, projector, etc.)

* Setup table with Tessels and Tessel modules

* Check-in attendees and hand out Tessels, to RSVPers only, as they arrive.

* Assist anyone needing help getting NodeJS installed

##### 6:30pm Start

* Opening remarks (thanks for coming, introduce staff, etc.)

* Ensure everyone has a laptop with NodeJS and working USB port (show of hands should suffice)

##### 6:45pm First Talk - Tim Ryan (Tessel)

* Tim will speak briefly about the Tessel device

* Start hacking!

* Hand out remaining Tessels to anyone that did not RSVP.

* Pair up non-laptop users with willing participants

* Continue offering assistance getting NodeJS installed for those that need it

##### 8:00 Finish

* Show and Tell for anyone that wants to show off

* Give aways

  * Physical copy of Pragmatic Version Control Using Git (courtesy of @dlindahl)

  * Physical copy of Javascript Pocket Reference (courtesy of @dlindahl)

  * Physical copy of Javascript: The Good Parts (courtesy of @dlindahl)

  * 3 new eBook copies of Javascript: The Good Parts (courtesy of our O'Reily sponsorship)

    Need full name and email address of winners  

  * Give away Nomad+JS tickets

    The "tickets" would be for the [March 17th meetup](http://nomadjavascript.com/march-2015/). @dlindahl will give away his slot so that two can attend the virtual meetup. All we need is full name and email address which will be forwarded to the Nomad+JS staff for registration.

* Collect Tessels from attendees

* Next meetup in February (18th or 25th)

  Ask for speaker volunteers or recommendations

* Announce BeerJS and CoffeeJS sub-events

  Watch Twitter (@sac_js & @beerjs_sac) or Meetup.com for news

* Get Tim to the train station NLT 9pm

**Comment by dlindahl** [comment]
Brandon @ the Hive says that they are fully booked, so we'll have to pivot and use Hacker Lab for at least our first meetup. Their calendar seems to indicate that the last two weeks are more or less available. I've update Technical Machine as to the status and have let me choose a date that works best for them.

**Comment by dlindahl** [comment]
Additionally, I've asked @a-axton to organize a quick meeting with Brandon and myself, Andy, and @samt (if you can make it) to discuss expectations about what we are trying to do and what Brandon is looking to host in his space.

**Comment by samt** [comment]
I am going to be in-town and flexible for meetings for the most part except for the first week in February.

**Comment by dlindahl** [comment]
I have been in contact with Technical Machine and have confirmed a reservation for 4 Hackathon kits. I will most likely be driving to Berkley to pick them up since its easier and I can better guarantee receipt of them.

I am still trying to get them to commit to a date so that I can then get something on the board with Hacker Lab. Hopefully that won't take much longer...

**Comment by dlindahl** [comment]
I've heard back from Tim with Technical Machine and I have floated the dates of Jan 27, 28, or 29. Based on The Hacker Lab's event calendar, they seem to be relatively free of anything that would interfere with our event.

@samt, since you probably know who to talk to, can you ask The Hacker Lab if we can hold an event there on one of those dates?

**Comment by samt** [comment]
I can get one of those dates scheduled.

**Comment by dlindahl** [comment]
@samt Just confirm that they are available. I'm waiting on confirmation from Technical Machine on one of those dates. I just want to make sure that the runway is clear, so to speak.

**Comment by samt** [comment]
Got it, will do :+1:

**Comment by dlindahl** [comment]
@samt Did you get a chance to talk with Hacker Lab yet?

**Comment by samt** [comment]
@dlindahl They said they would get back to me last week.... I'll ping them again today.

**Comment by dlindahl** [comment]
@samt Heard back from Tim:

> In order of preference, the 29, 28, then 27 would work best for me.

The faster we lock this in, the better. That way we have time to promote it. We are already cutting it close as it is :grimacing: :beers:

**Comment by samt** [comment]
Hacker Lab is good for the Thursday 29th.

I let them know that we'll be doing our own marketing and RSVP system (so it wont go on Hackerlab's meetup and cross-RSVPing due to the strict limit).

**Comment by dlindahl** [comment]
Awesome! :+1: :beers: :tada: 

Did you happen to discuss a time? I told Tim 6:30pm since that seems to be the usual time. Also, do we have to do anything special to reserve the front room? I want to make sure we don't get relegated to the conference room.

**Comment by samt** [comment]
We have the front area, I let him know there might be as many as 40 people. I said 6 initially, but 6:30 is also good.

Also an FYI for the future:
>  If they need help marketing we usually charge a space fee of $100 per hour for events like this.  But if they don't want us to promote it then everything is fine.

As we are not having them do marketing, it wont cost anything.

**Comment by a-axton** [comment]
I remember the tessel girl at node-bots saying that if you wanted wifi for the tessel you had to create a hotspot on your phone (the space had a similar wifi check-in)

**Comment by dlindahl** [comment]
Yeah, I need to think of a solution for that... 

@samt Can you check with the Hacker Lab people to see if they can work with us to create a temporary work around to their Terms of Service check on the wi-fi?

I know you can create a network in OSX. Does anyone know if that can bridge to the Internet?

**Comment by a-axton** [comment]
Did a quick google search and it seems you can. http://computers.tutsplus.com/tutorials/quick-tip-use-your-mac-as-a-wi-fi-hotspot-and-more--mac-46462

**Comment by dlindahl** [comment]
@a-axton :+1: Looks like that requires an ethernet connection though. I'll have to remember to bring a cable. Are there ethernet ports in that main room?

**Comment by a-axton** [comment]
Ya, the article wasn't super clear if that was a requirement. It says, "(You wouldn't need to follow this tip if you already have a Wi-Fi connection!)". We'll have to test it out I guess

**Comment by samt** [comment]
I know right now that they absolutely will not provide that. I can bring a spare router to hook up to their hard line if the wifi network. There are a few drops there, dunno if active. I can scout out the place this week for good ones. There are some in the rooms next to meeting area we can always tie into.

**Comment by dlindahl** [comment]
@samt I am going to be at Hacker Lab tonight for Code4Sac's web scraping talk. Do you want to meet me there with your router and experiment with the network?

**Comment by dlindahl** [comment]
@samt Also, Tim is arriving by train and gets in at ~5:30pm. Will I have a problem getting in to Hacker Lab before 6? I know the door is usually unlocked (or monitored) for meetups, but since we ARE the meetup, I'm not sure how that works.

**Comment by samt** [comment]
I'm afraid I absolutely cannot make it tonight. Normally my nights are 
free, but this one has been booked for a while. I will be at hackerlab 
early with my networking tools and such and we should be able to get it 
working.

**Comment by samt** [comment]
You should have no problem getting in. I plan to be there at around 5-5:15pm

**Comment by dlindahl** [comment]
:+1: I'll see if I can dig up some ethernet and a router and try it myself tonight. In the event that doesn't happen, proceed with your own test tomorrow.

We should be arriving around 5:30@HL. Keep an eye on the door for us!

**Comment by a-axton** [comment]
we have a wifi router and cables at the office if you need to borrow some

**Comment by dlindahl** [comment]
@a-axton Even if we figure it out, please bring it anyway in the event we need a backup. Also, please invite the rest of Rocket Dept. to come! They just need to RSVP in order to claim a Tessel

**Comment by a-axton** [comment]
will do, so excited!!

**Comment by dlindahl** [comment]
@samt I was unable to find an ethernet port in the time I had available last night. I'm hoping you will have better luck than I did. I should be there around 5pm to help out. Do you need any additional networking supplies to pull this off? I have some cables and maybe an Airport Extreme somewhere.

@a-axton Please secure your router as well in case we end up needing it, you'll know where it is.

**Comment by samt** [comment]
Ill be bringing a router, a bunch of cables, raw cables, crimpers, ends,
switches, other things. Bring your things too.

Any specifics on the WiFi SSID?

**Comment by dlindahl** [comment]
`tessel`? `sac_js`?

**Comment by samt** [comment]
This went really well, the turnout was great. I hope Tim enjoyed presenting there too, would love to have him back. Please send him all our thanks.

Got lots of positive responses so far and Richard mentioned something interesting too: 

> that was a good group you got, too.
> no dopes.
> everyone was with it.

Which I totally agree with. We did have a good group, the 15-20 or so active people we had working on it were all into it and seemed to be enjoying themselves. 

For the future Tim mentioned to me the possibility of a larger hackathon where participants would keep their equipment at the end (I would assume this would be built into the cost of an entry fee combined with subsidizing the hardware costs on their end). 

In any case, I would call this one a success :+1: Thanks @dlindahl for getting Tim and Tessel here and please send our thanks to Tim for coming out.

**Comment by dlindahl** [comment]
Agreed. This went fantastic.

I am sure we can work out something w/ Tessel, but it would definitely require ticket purchases which is a whole new level of logistics that I'm not quite sure we're up to yet. AFAIK, Tessel hasn't given out any hardware unlike Spark, Arduino, etc. I would definitely consider the idea though.

Tim said that he'd be interested in coming back to SAC as either an invited guest or as an attendee, so there is certainly future possibilities there.

Thanks for gathering that feedback, @samt. Also, thank you and @a-axton for your help setting up and tearing down. All that traffic made getting there a complete PITA and Tim & I were dilly-dallying at teardown so we were pushing it with his return train. I'd like to apologize for bouncing so quickly, but we were running out of time. Your first round of :beer: is on me for BeerJS!

And now on to planning February!
