### ISSUE TITLE
React Workshop with Steven Luscher (Instagram)

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#31]
**Date:** Saturday, July 18th
**Time:** 9:00am - 5:00pm
**Location:** UC Davis Extension, Room 200
**Tickets:** https://ti.to/sacjs/reactjs-workshop
* * *

## Overview

At JSConf, I talked to Tom Occhino from Facebook about getting us in touch with someone that coulf run a React Workshop here in Sacramento. He got me in touch with Steven Luscher from the Instagram Web Team. He teaches React to new hires at Facebook. He has offered to run a modified version of a workshop that he delivered in Vancouver at the Polyglot conference. That workshop was 8-hours long, so we might alter the time commitment based on user feedback.

This workshop would be in lieu of our normal Tuesday meetup because I am not a robot and won't have time to book speakers for two events :smile: 

##### Pre-workshop

* If libs need to be pre-installed (npm, node, etc.), communicate to attendees

##### Day Before

* Ensure Steven arrived OK

  He says he will be coming in late

* Get cooler prepped
* Costco Run for beverages w/ @samt (#34)

##### 8:00am - Day of Preparation

* Get ice
* Setup room
* Receive breakfast delivery from Noah's Bagels (#34)
* Setup breakfast
* Setup refreshments for the day

##### 9:00am - Check-in

* Handle check-in/registration
* If libs need to be pre-installed (npm, node, etc.), make sure attendees have that working
* Swag?
  * I have tons of React stickers, a good number of Facebook stickets, and some Instagram stickers
  * Maybe Steven can bring some Facebook tshirts, etc up with him

##### 10:00am - Start

* Welcome guests
* CoC
* Introduce Steven

##### 10:05am Workshop

* Do the thing

##### 11:20am - Prep Lunch

* Drive to Chipotle to pick up order (@samt [has Order #] and @a-axton)

  1831 Capitol Ave
  Sacramento, CA 95814

* Setup lunch

  Unpack, arrange chafing dishes, add water to pan, light pan fuel, etc.

##### 12:00pm - Catered Lunch

* Eat the Chipotle

##### 12:45pm - Workshop

* Do the thing

##### 2:45pm - Break

* Snacks?

##### 3:00pm - Workshop

* Do the thing

##### 4:00pm - Closing

* Q&A?
* Thank Steven
* Thank sponsors

##### Post-workshop

* Optional staff/attendee dinner/BeerJS
* Drop off Steven at the train station in time for the 9:10pm train

## Tasks

* [x] Find a venue

  [UC Davis Extension](https://extension.ucdavis.edu/)
  Sutter Square Galleria Center
  2901 K St
  Sacramento, CA 95816
  Room 200

* [x] Find a time

  9am - 5pm

* [x] Find sponsor for lodging

  ~~Since Steven will be traveling 4-hours in one direction, he asked if someone would be willing to host him overnight. I think we can go one step further and get him a hotel room near the train station. I'm hoping that we can get that covered via a sponsorship. Worst case, I'll pay out of pocket.~~

  Facebook will be covering Steven's lodging expenses

* [x] Find sponsor for food and beverages

  We have sponsorship money coming in from Autodesk ~~and possibly more from Stone Cobra and TEKSystems if needed. Still awaiting confirmation.~~

  Barring any surprises, the Autodesk money should cover the entire event

* [x] Find support staff

  Anyone we know that is proficient in React is welcome to act as staff for this event. At the very least, I'd like to have the following on hand:
  * [x] @dlindahl
  * [x] @a-axton 
  * [x] @samt  
  * [x] @eporcello (Reacto organizer)
  * [x] @MoonTahoe

* [x] Determine if a fee is necessary

  ~~Since this will be the most logistically challenging event we've put on, I'd like to explore the idea of selling tickets for at least a $5 non-refundable fee. Since ticket purchasers will have some skin in the game, it will help deter no-shows. In addition, the fee can help offset any expenses we incur. Any profits would go to an as yet unnamed local STEM-like organization.~~

  We will be charging $10 per ticket with a 50%-off discount for the first 5 registrants at the June 23rd Meetup (#30). This will be handled by a Tito account that I have setup.

**Comment by dlindahl** [comment]
Aaron Winters said [on #sactech Slack](https://sac-tech.slack.com/archives/general/p1433202181000043):

> Art Institute is usually very supportive of hosting outside groups Derek. Talk to Bill Mead.

**Comment by eporcello** [comment]
This sounds amazing! 

A few things:
* My husband, Alex Banks (@MoonTahoe), knows React well also and can help day of.
* Do we know when we'd like to hold the event? Saturday July 11 stands out as a good date for Alex and me.
* Could Steven come up the night before so that we could maybe start a bit earlier in the day? It might be nicer for him to teach after sleeping too!
* It'd be cool to do t-shirts or something as swag - I could ask around about getting them donated.
* We can donate the hotel room.

**Comment by dlindahl** [comment]
@eporcello: added @MoonTahoe to the list of helpers

I'm still working with Steven on getting a date locked in. If he's able to come up on Friday so we can start early-ish on Saturday, I'm ok with that.

If FB has leftover swag from events, hopefully Steven can bring those with him. I'm not sure we need anything custom for this event if that's what you mean. I can speak to their event coordinator to see if he has anything to offer.

**Comment by dlindahl** [comment]
I pinged Stone Cobra to see if they'd be interested in sponsoring. They had a developer at our April meetup say that they were actively looking for React developers.

**Comment by samt** [comment]
:+1: Let me know if I can do anything to assist.

**Comment by dlindahl** [comment]
Heard back from Steven. We're tentatively schedule for July 18th. Once we get a venue locked in, everything else should fall into place.

* @samt is asking at UC Davis Extension
* @a-axton is asking at The Hive and VSP: The Shop

I've updated the content of this issue to reflect the current state.

**Comment by eporcello** [comment]
Awesome! Let me know if we can help in any way.

**Comment by dlindahl** [comment]
@samt says our space at UCD Extension is almost set. We're waiting on confirmation and clarification about parking validation. If they can't cover parking, ticket prices or an extra sponsor should more than cover it.

Steven sent along this link that shows a syllabus that he's used in past events: https://github.com/steveluscher/react-polyglot-conf-2014#syllabus

@eporcello we have you penciled in as an on-site helper along with myself, @a-axton, and @samt. Aside from that, let me know if you want to say something about Reacto at the end so I can plan accordingly.

Other than promoting the event and day-of check-in, I'm not sure there is a whole lot of work for us to do. Maybe some coordination with caterers will be required as day-of, but I'm not sure we are organized enough yet to know :smile:

**Comment by dlindahl** [comment]
@samt heard back from UCD and we're good to:

> UC Davis Extension
> Room 305
> Saturday, July 18th, from 8am - 6pm (1hr for setup/teardown)
> Cost: $180 (they're splitting the fee with us)

I'm going to officially announce via twitter and meetup and I'll post the registration link here as well.

**Comment by dlindahl** [comment]
Here is the link for ticket purchasing: https://ti.to/sacjs/reactjs-workshop

Share with everyone you know!

**Comment by dlindahl** [comment]
@sacjs/staff: Please register for a Staff ticket at https://ti.to/sacjs/reactjs-workshop/with/suvjfenukxi
