### ISSUE TITLE
Workshop 2: International NodeBots Day

### ISSUE THREAD

**Issue by dlindahl** [sacjs/sacjs.github.io#63]
**Date:** Saturday, July 30th
**Time:** TBD ~~9:00am - 5:00pm~~
**Location:** TBD ~~UC Davis Extension, Room 200~~
**Tickets:** TBD ~~https://ti.to/sacjs/reactjs-workshop~~
* * *

## Overview

TBD (https://github.com/nodebots/nodebotsday)

##### Pre-workshop

TBD

##### Day Before

TBD

##### ~~8:00am~~ - Day of Preparation

TBD

##### ~~9:00am~~ - Check-in

TBD

##### ~~10:00am~~ - Start

* Welcome guests
* CoC

TBD

##### ~~10:05am~~ Workshop

* Do the thing

##### ~~11:20am~~ - Prep Lunch

TBD

##### ~~12:00pm~~ - Catered Lunch

TBD

##### ~~12:45pm~~ - Workshop

TBD

##### ~~2:45pm~~ - Break

TBD

##### ~~3:00pm~~ - Workshop

TBD

##### ~~4:00pm~~ - Closing

TBD

##### Post-workshop

* Optional staff/attendee dinner/BeerJS

TBD

## Tasks

* [ ] Find a venue

* [ ] Find a time

* [ ] Find sponsor for food and beverages

* [ ] Find support staff

  * [x] @dlindahl
  * [ ] @a-axton 
  * [x] @samt  

* [ ] Determine if a fee is necessary

**Comment by samt** [comment]
@dlindahl 

* How much for each kit?
* How many kits?
* How much are we budgeting for meals?
